config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tools#index'
  resources :tools do
    get :update_translation, on: :member
    post :webhook, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tool.rb
class Tool < ApplicationRecord
  validates :name, :language, presence: true

  def update_translation
    # can be replaced with your username, repository name
    github = GithubService.new('railstesh', 'coding_challenge')
    lokalise = LokaliseService.new('79f58e3b769ce941f75bab97d7fb17f118cf5524', '944415995ecebd933b7b96.13035535')
    spec_data = github.read_file(name, language)

    # handle a special key 'tool_version'
    sp_key = key_info["#{name.upcase}_tool_version"]
    if sp_key
      translation = lokalise.translation(sp_key, language)
      spec_data['tool_version'] = translation
      key_info.delete("#{name.upcase}_tool_version")
    end

    key_info.each do |key, k_id|
      translation = lokalise.translation(k_id, language)
      write_value(spec_data, key, translation)
    end

    file = File.open("#{name}.#{language}.json", 'w') do |f|
      f.write(JSON.pretty_generate(spec_data))
    end

    branch_name = "tool-#{id}-#{name}.#{language}.json"
    github.create_push_branch(branch_name)
    github.create_pr(branch_name)
  end

  private

  def write_value(hash, x_value, new_value)
    recurse(hash, x_value.sub(/^#{name}_/i, '').split('_'), new_value)
  end

  def recurse(hash, keys, new_value)
    k = keys.shift
    keys.empty? ? (hash[k] = new_value) : recurse(hash[k], keys, new_value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  protect_from_forgery except: :webhook
  before_action :set_tool, only: %i[show edit update destroy update_translation]

  def index
    @tools = Tool.all
  end

  def show; end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)

    respond_to do |format|
      if @tool.save
        format.html do
          # can be replaced with your username, repository name
          spec_data = GithubService.new('railstesh', 'coding_challenge').read_file(@tool.name, @tool.language)
          keys_data = LokaliseService.new('79f58e3b769ce941f75bab97d7fb17f118cf5524', '944415995ecebd933b7b96.13035535').create_keys(spec_data, @tool.language)
          @tool.update(json_spec: spec_data, key_info: keys_data)
          redirect_to @tool, notice: 'Tool created successfully'
        end
      else
        format.html { render :new }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html do
          redirect_to @tool,
                      notice: 'Tool was successfully updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tool.destroy

    redirect_to tools_path
  end

  def update_translation
    LokaliseJob.perform_later(@tool.id)
    redirect_to tools_path,
                notice: 'Updating process has initiated. It can take up to 5 minutes.'
  end

  # https://coding_challenge.ngrok.io/tools/webhook
  def webhook
    pr = params[:pull_request]
    if pr[:state].eql?('closed') && pr[:merged].eql?(true)
      # title will be like: tool-1-BMI.en.json | tool-<id>-<file_name>
      title = pr[:title]
      id = title.split('-')[1]
      file_name = title.sub(/.*-\d*-/, '')
      file_content = JSON.parse(File.read(file_name))
      tool = Tool.find(id)
      tool.update_attribute(:json_spec, file_content)

      render json: { status: 200 }
    end
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :language, :json_spec)
  end

  def set_tool
    @tool = Tool.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tools/_form.html.erb
<%= form_with(model: tool, local: true) do |form| %>
  <% if tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
      <% tool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :language %>
  <%= form.text_field :language %>
  <%= form.submit "#{params[:action].eql?('new') ? 'Create' : 'Update'} Tool" %>
  <%= link_to 'Cancel', tools_path %>
<% end %>

app/views/tools/_tool.html.erb
<tr>
  <td><%= tool.id %></td>
  <td><%= tool.name %></td>
  <td><%= tool.language %></td>
  <td><%= tool.json_spec.to_s.truncate(50) %></td>
  <td><%= link_to 'Show', tool %></td>
  <td><%= link_to 'Edit', edit_tool_path(tool) %></td>
  <td><%= link_to 'Destroy', tool, method: :delete, data: { confirm: 'Are you sure?' } %>
  <td><%= link_to 'Update Translation', update_translation_tool_path(tool) %></td>
</tr>

app/views/tools/edit.html.erb
<%= render 'form', tool: @tool %>

app/views/tools/index.html.erb
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Language</th>
      <th>JSON Spec</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'tool', collection: @tools %>
  </tbody>
</table>

<%= link_to 'New Tool', new_tool_path %>

app/views/tools/new.html.erb
<%= render 'form', tool: @tool %>

app/views/tools/show.html.erb
<div>
  <p>Name: <%= @tool.name %></p>
  <p>Language: <%= @tool.language %></p>
  <p>JSON spec: <%= @tool.json_spec %></p>
</div>
<%= link_to 'Back', tools_path %> | <%= link_to 'edit', edit_tool_path(@tool) %>